# Generated by Django 4.0 on 2023-12-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('Id', models.AutoField(db_column='adridpk', primary_key=True, serialize=False)),
                ('StreetNumber', models.CharField(blank=True, db_column='adrstreetnumber', max_length=255, null=True)),
                ('HouseNumber', models.CharField(blank=True, db_column='adrhousenumber', max_length=255, null=True)),
                ('GpsAddress', models.CharField(blank=True, db_column='adrgpsaddress', max_length=255, null=True)),
                ('CreationDate', models.DateField(blank=True, db_column='adrcreateddate', null=True)),
                ('LastEditDate', models.DateTimeField(blank=True, db_column='adrlasteditdate', null=True)),
            ],
            options={
                'db_table': 'tbladdresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('Id', models.AutoField(db_column='ctyidpk', primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, db_column='ctyname', max_length=255, null=True)),
                ('ShortName', models.CharField(blank=True, db_column='ctyshtname', max_length=10, null=True)),
                ('Code', models.CharField(blank=True, db_column='ctycode', max_length=20, null=True)),
                ('CreationDate', models.DateField(blank=True, db_column='ctycreateddate', null=True)),
                ('LastEditDate', models.DateTimeField(blank=True, db_column='ctylasteditdate', null=True)),
            ],
            options={
                'db_table': 'tblcountries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('Id', models.AutoField(db_column='staidpk', primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, db_column='staname', max_length=255, null=True)),
                ('ShortName', models.CharField(blank=True, db_column='stashtname', max_length=10, null=True)),
                ('CreationDate', models.DateField(blank=True, db_column='stacreateddate', null=True)),
                ('LastEditDate', models.DateTimeField(blank=True, db_column='stalasteditdate', null=True)),
            ],
            options={
                'db_table': 'tblstates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('Id', models.AutoField(db_column='tltidpk', primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, db_column='tltname', max_length=255, null=True)),
                ('ShortName', models.CharField(blank=True, db_column='tltshtname', max_length=255, null=True)),
                ('CreationDate', models.DateField(blank=True, db_column='tltcreationdate', null=True)),
                ('LastEditDate', models.DateTimeField(blank=True, db_column='tltlasteditdate', null=True)),
            ],
            options={
                'db_table': 'tbltitles',
                'managed': False,
            },
        ),
    ]
