# Generated by Django 4.2.6 on 2023-10-21 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcartitem',
            fields=[
                ('crtitemidpk', models.AutoField(db_column='crtItemIdpk', primary_key=True, serialize=False)),
                ('crtitemquantity', models.DecimalField(db_column='crtItemQuantity', decimal_places=2, max_digits=10)),
                ('crtitemprice', models.DecimalField(db_column='crtItemPrice', decimal_places=2, max_digits=10)),
                ('crtitemaddeddate', models.DateField(blank=True, db_column='crtItemAddedDate', null=True)),
            ],
            options={
                'db_table': 'tblcartitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcustomer',
            fields=[
                ('custidpk', models.AutoField(db_column='custIdpk', primary_key=True, serialize=False)),
                ('custfirstname', models.CharField(blank=True, db_column='custFirstName', max_length=255, null=True)),
                ('custlastname', models.CharField(blank=True, db_column='custLastName', max_length=255, null=True)),
                ('custothername', models.CharField(blank=True, db_column='custOtherName', max_length=255, null=True)),
                ('custemail', models.CharField(blank=True, db_column='custEmail', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblcustomer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcustomeraddress',
            fields=[
                ('custaddressidpk', models.AutoField(db_column='custAddressIdpk', primary_key=True, serialize=False)),
                ('custstreetnumber', models.CharField(blank=True, db_column='custStreetNumber', max_length=255, null=True)),
                ('custhousenumber', models.CharField(blank=True, db_column='custHouseNumber', max_length=255, null=True)),
                ('custgpsaddress', models.CharField(blank=True, db_column='custGpsAddress', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblcustomeraddress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcustomercountry',
            fields=[
                ('custcountryidpk', models.AutoField(db_column='custCountryIdpk', primary_key=True, serialize=False)),
                ('custcountryname', models.CharField(blank=True, db_column='custCountryName', max_length=255, null=True)),
                ('custcountryshtname', models.CharField(blank=True, db_column='custCountryShtName', max_length=10, null=True)),
                ('custcountrycode', models.CharField(blank=True, db_column='custCountryCode', max_length=20, null=True)),
            ],
            options={
                'db_table': 'tblcustomercountry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcustomerstate',
            fields=[
                ('custstateidpk', models.AutoField(db_column='custStateIdpk', primary_key=True, serialize=False)),
                ('custstatename', models.CharField(blank=True, db_column='custStateName', max_length=255, null=True)),
                ('custstateshtname', models.CharField(blank=True, db_column='custStateShtName', max_length=10, null=True)),
            ],
            options={
                'db_table': 'tblcustomerstate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbldiscount',
            fields=[
                ('field_discountidpk', models.AutoField(db_column='\xa0discountIdpk', primary_key=True, serialize=False)),
                ('field_discountname', models.CharField(db_column='\xa0discountName', max_length=255)),
                ('field_discountpercentage', models.DecimalField(db_column='\xa0discountPercentage', decimal_places=2, max_digits=10)),
                ('field_discounttype', models.CharField(db_column='\xa0discountType', max_length=255)),
            ],
            options={
                'db_table': 'tbldiscount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblgender',
            fields=[
                ('gndidpk', models.AutoField(db_column='gndIdpk', primary_key=True, serialize=False)),
                ('gndshtname', models.CharField(blank=True, db_column='gndShtName', max_length=2, null=True)),
                ('gndname', models.CharField(blank=True, db_column='gndName', max_length=6, null=True)),
                ('gndactive', models.TextField(blank=True, db_column='gndActive', null=True)),
                ('gndlasteditdate', models.DateTimeField(blank=True, db_column='gndLastEditDate', null=True)),
            ],
            options={
                'db_table': 'tblgender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblinventory',
            fields=[
                ('invid', models.AutoField(db_column='invId', primary_key=True, serialize=False)),
                ('invitemprdidfk', models.IntegerField(blank=True, db_column='invItemPrdIdfk', null=True)),
                ('invitemsupplieridfk', models.IntegerField(blank=True, db_column='invItemSupplierIdfk', null=True)),
                ('invitemprice', models.DecimalField(blank=True, db_column='invItemPrice', decimal_places=2, max_digits=10, null=True)),
                ('invitemmodelnumber', models.CharField(blank=True, db_column='invItemModelnumber', max_length=255, null=True)),
                ('invitemwarranty', models.CharField(blank=True, db_column='invItemWarranty', max_length=255, null=True)),
                ('invitemdimensions', models.CharField(blank=True, db_column='invItemDimensions', max_length=255, null=True)),
                ('invitemreleasedate', models.DateField(blank=True, db_column='invItemReleaseDate', null=True)),
                ('invitemweight', models.CharField(blank=True, db_column='invItemWeight', max_length=255, null=True)),
                ('invitemcolor', models.CharField(blank=True, db_column='invItemColor', max_length=255, null=True)),
                ('invitemfeatures', models.CharField(blank=True, db_column='invItemFeatures', max_length=255, null=True)),
                ('invitemspecifications', models.CharField(blank=True, db_column='invItemSpecifications', max_length=255, null=True)),
                ('invitemquantity', models.IntegerField(blank=True, db_column='invItemQuantity', null=True)),
                ('invitemproductdescription', models.CharField(blank=True, db_column='invItemProductDescription', max_length=255, null=True)),
                ('invitemproductreorderpoint', models.IntegerField(blank=True, db_column='invItemProductReorderPoint', null=True)),
                ('invitemproductreorderquantity', models.IntegerField(blank=True, db_column='invItemProductReorderQuantity', null=True)),
            ],
            options={
                'db_table': 'tblinventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblorder',
            fields=[
                ('ordidpk', models.AutoField(db_column='ordIdpk', primary_key=True, serialize=False)),
                ('ordcustidfk', models.IntegerField(blank=True, db_column='ordCustIdfk', null=True)),
                ('orddate', models.DateField(blank=True, db_column='ordDate', null=True)),
                ('ordshippingaddressid', models.IntegerField(blank=True, db_column='ordShippingAddressId', null=True)),
                ('ordpaymentstatusid', models.IntegerField(blank=True, db_column='ordPaymentStatusID', null=True)),
                ('ordtotal', models.DecimalField(blank=True, db_column='ordTotal', decimal_places=2, max_digits=10, null=True)),
                ('ordnotes', models.CharField(blank=True, db_column='ordNotes', max_length=255, null=True)),
                ('orddeliverystatusid', models.IntegerField(blank=True, db_column='ordDeliveryStatusID', null=True)),
                ('ordstatusidfk', models.IntegerField(blank=True, db_column='ordStatusIdfk', null=True)),
            ],
            options={
                'db_table': 'tblorder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblorderitems',
            fields=[
                ('itemid', models.AutoField(db_column='itemID', primary_key=True, serialize=False)),
                ('itemshippingtax', models.DecimalField(blank=True, db_column='itemShippingTax', decimal_places=2, max_digits=10, null=True)),
                ('itemquantity', models.DecimalField(blank=True, db_column='itemQuantity', decimal_places=2, max_digits=10, null=True)),
                ('itemprice', models.DecimalField(blank=True, db_column='itemPrice', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'tblorderitems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblpaymentstatus',
            fields=[
                ('paymentstatusidpk', models.AutoField(db_column='paymentStatusIdpk', primary_key=True, serialize=False)),
                ('paymentstatus', models.CharField(blank=True, db_column='paymentStatus', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblpaymentstatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblproduct',
            fields=[
                ('prdidpk', models.AutoField(db_column='prdIdpk', primary_key=True, serialize=False)),
                ('prdname', models.CharField(blank=True, db_column='prdName', max_length=255, null=True)),
                ('prddescription', models.CharField(blank=True, db_column='prdDescription', max_length=255, null=True)),
                ('prdprice', models.DecimalField(blank=True, db_column='prdPrice', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'tblproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblproductbrand',
            fields=[
                ('prdbrandidpk', models.AutoField(db_column='prdBrandIdpk', primary_key=True, serialize=False)),
                ('prdbrandname', models.CharField(blank=True, db_column='prdBrandName', max_length=255, null=True)),
                ('prdbranddesc', models.CharField(blank=True, db_column='prdBrandDesc', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblproductbrand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblproductcategory',
            fields=[
                ('prdcategoryidpk', models.AutoField(db_column='prdCategoryIdpk', primary_key=True, serialize=False)),
                ('prdcategoryname', models.CharField(blank=True, db_column='prdCategoryName', max_length=255, null=True)),
                ('prdcategorydesc', models.CharField(blank=True, db_column='prdCategoryDesc', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblproductcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblproductsubcategory',
            fields=[
                ('prdsubcategoryidpk', models.AutoField(db_column='prdSubCategoryIdpk', primary_key=True, serialize=False)),
                ('prdsubcategoryname', models.CharField(blank=True, db_column='prdSubCategoryName', max_length=255, null=True)),
                ('prdsubcategorydesc', models.CharField(blank=True, db_column='prdSubCategoryDesc', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblproductsubcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblpurchases',
            fields=[
                ('pchidpk', models.AutoField(db_column='pchIdpk', primary_key=True, serialize=False)),
                ('pchammount', models.DecimalField(blank=True, db_column='pchAmmount', decimal_places=2, max_digits=10, null=True)),
                ('pchpurchasedate', models.DateField(blank=True, db_column='pchPurchaseDate', null=True)),
                ('pchtypeid', models.IntegerField(blank=True, db_column='pchTypeId', null=True)),
                ('pchlasteditdate', models.DateTimeField(blank=True, db_column='pchLastEditDate', null=True)),
            ],
            options={
                'db_table': 'tblpurchases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblreturns',
            fields=[
                ('field_returnidpk', models.AutoField(db_column='\xa0returnIdPK', primary_key=True, serialize=False)),
                ('field_customerid', models.IntegerField(db_column='\xa0customerId')),
                ('field_orderid', models.IntegerField(db_column='\xa0orderId')),
                ('field_productid', models.IntegerField(db_column='\xa0productId')),
                ('field_returndate', models.DateField(db_column='\xa0returnDate')),
                ('field_returnreason', models.CharField(db_column='\xa0returnReason', max_length=255)),
                ('field_refundstatus', models.CharField(db_column='\xa0refundStatus', max_length=255)),
            ],
            options={
                'db_table': 'tblreturns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblreviews',
            fields=[
                ('rwvidpk', models.AutoField(db_column='rwvIdpk', primary_key=True, serialize=False)),
                ('rwvuseridfk', models.IntegerField(blank=True, db_column='rwvUserIdfk', null=True)),
                ('rwvproductidfk', models.IntegerField(blank=True, db_column='rwvProductIdfk', null=True)),
                ('rwvreveiewcontent', models.CharField(blank=True, db_column='rwvReveiewContent', max_length=255, null=True)),
                ('rwvratings', models.DecimalField(blank=True, db_column='rwvRatings', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'tblreviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblshippingmethod',
            fields=[
                ('field_shippingmethodidpk', models.AutoField(db_column='\xa0shippingMethodIdpk', primary_key=True, serialize=False)),
                ('field_shippingmethodname', models.CharField(db_column='\xa0shippingMethodName', max_length=255)),
                ('field_shippingcost', models.DecimalField(db_column='\xa0shippingCost', decimal_places=2, max_digits=10)),
                ('field_shippingdeliverytime', models.CharField(db_column='\xa0shippingDeliveryTime', max_length=255)),
            ],
            options={
                'db_table': 'tblshippingmethod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblsupplier',
            fields=[
                ('splidpk', models.AutoField(db_column='splIdpk', primary_key=True, serialize=False)),
                ('splname', models.CharField(blank=True, db_column='splName', max_length=50, null=True)),
                ('spladdress', models.CharField(blank=True, db_column='splAddress', max_length=100, null=True)),
                ('splcontact', models.CharField(blank=True, db_column='splContact', max_length=15, null=True)),
                ('splcontract', models.TextField(blank=True, db_column='splContract', null=True)),
            ],
            options={
                'db_table': 'tblsupplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbltax',
            fields=[
                ('field_taxidpk', models.AutoField(db_column='\xa0taxIdpk', primary_key=True, serialize=False)),
                ('field_taxname', models.CharField(db_column='\xa0taxName', max_length=255)),
                ('field_taxpercentage', models.DecimalField(db_column='\xa0taxPercentage', decimal_places=2, max_digits=10)),
                ('field_taxtype', models.CharField(db_column='\xa0taxType', max_length=255)),
            ],
            options={
                'db_table': 'tbltax',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbltitle',
            fields=[
                ('tltidpk', models.AutoField(db_column='tltIdpk', primary_key=True, serialize=False)),
                ('tltname', models.CharField(blank=True, db_column='tltName', max_length=255, null=True)),
                ('tltshtname', models.CharField(blank=True, db_column='tltShtName', max_length=255, null=True)),
                ('tltcreationdate', models.DateField(blank=True, db_column='tltCreationDate', null=True)),
                ('tltlasteditdate', models.DateTimeField(blank=True, db_column='tltLastEditDate', null=True)),
            ],
            options={
                'db_table': 'tbltitle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbluser',
            fields=[
                ('usridpk', models.AutoField(db_column='usrIdpk', primary_key=True, serialize=False)),
                ('usrname', models.CharField(blank=True, db_column='usrName', max_length=25, null=True, unique=True)),
                ('usraddress', models.CharField(blank=True, db_column='usrAddress', max_length=25, null=True)),
                ('usrpassword', models.CharField(blank=True, db_column='usrPassword', max_length=25, null=True)),
                ('usrisadmin', models.IntegerField(blank=True, db_column='usrIsAdmin', null=True)),
                ('usrisemployee', models.IntegerField(blank=True, db_column='usrIsEmployee', null=True)),
                ('usrismanager', models.IntegerField(blank=True, db_column='usrIsManager', null=True)),
                ('usrisactive', models.IntegerField(blank=True, db_column='usrIsActive', null=True)),
                ('usrregistrationdate', models.DateField(blank=True, db_column='usrRegistrationDate', null=True)),
                ('usrlasteditdate', models.DateTimeField(blank=True, db_column='usrLastEditDate', null=True)),
            ],
            options={
                'db_table': 'tbluser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblshoppingcart',
            fields=[
                ('cartidpk', models.OneToOneField(db_column='cartIdpk', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='database.tblcustomer')),
                ('custidfk', models.IntegerField(db_column='custIdfk')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tblshoppingcart',
                'managed': False,
            },
        ),
    ]
