# Generated by Django 4.0 on 2023-12-20 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Id', models.AutoField(db_column='prdidpk', primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, db_column='prdname', max_length=255, null=True)),
                ('Description', models.CharField(blank=True, db_column='prddescription', max_length=255, null=True)),
                ('Price', models.DecimalField(blank=True, db_column='prdprice', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'tblproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('Id', models.AutoField(db_column='prdbrandidpk', primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, db_column='prdbrandname', max_length=255, null=True)),
                ('Description', models.CharField(blank=True, db_column='prdbranddesc', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblproductbrand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('Id', models.AutoField(db_column='prdcategoryidpk', primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, db_column='prdcategoryname', max_length=255, null=True)),
                ('Description', models.CharField(blank=True, db_column='prdcategorydesc', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblproductcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('Id', models.AutoField(db_column='prdsubcategoryidpk', primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, db_column='prdsubcategoryname', max_length=255, null=True)),
                ('Description', models.CharField(blank=True, db_column='prdsubcategorydesc', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblproductsubcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('Id', models.AutoField(db_column='prdimageidpk', primary_key=True, serialize=False)),
                ('ImageUrl', models.FileField(db_column='prdimageurl', upload_to='')),
                ('UploadedOn', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ForeignKey(db_column='prdimageprdidfk', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce_Product.product')),
            ],
            options={
                'db_table': 'tblproductimage',
                'managed': True,
            },
        ),
    ]
