# Generated by Django 4.0 on 2023-12-20 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('Id', models.AutoField(db_column='prdimageidpk', primary_key=True, serialize=False)),
                ('ImageUrl', models.FileField(upload_to='')),
                ('UploadedOn', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ForeignKey(db_column='prdimageprdidfk', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce_Product.product')),
            ],
        ),
    ]
