# Generated by Django 4.0 on 2023-12-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_Product', '0002_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
    ]
