# Generated by Django 4.0 on 2023-12-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_Product', '0003_alter_productimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'managed': True},
        ),
    ]
