# Generated by Django 4.0 on 2023-12-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_Product', '0004_alter_productimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='ImageUrl',
            field=models.FileField(db_column='prdimageurl', upload_to=''),
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='tblproductimage',
        ),
    ]
